name: Fetch Upstream

on:
   push:
   pull_request:
   schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  fetch-upstream:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Fetch Upstream
      uses: rumenmitrev/fetch-upstream@master
      with:
        upstream: OpenDroneMap/WebODM
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_FOR_AUTH_GIT }}      
